# This is a config for E2B sandbox template.
# You can use template ID (b20qkwewj3501g82uj9s) or template name (vibe-nextjs-test-yokong-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-yokong-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-yokong-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-yokong-2')

team_id = "95b263c3-0bc3-4cd8-b0f6-55c0e32eb903"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-yokong-2"
template_id = "b20qkwewj3501g82uj9s"
